/*
 * This source file was generated by the Gradle 'init' task
 */
package worlddung;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        WorldDungeon classUnderTest = new WorldDungeon();
        
    }
}
